services:
  - type: web
    name: pvt-partners-website
    env: static
    buildCommand: npm run build
    staticPublishPath: dist/public
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
